USStates_en = {
	AL : "Alabama",
	AK : "Alaska",
	AZ : "Arizona",
	AR : "Arkansas",
	AS : "American Samoa",
	CA : "California",
	CO : "Colorado",
	CT : "Connecticut",
	DC : "Washington, D.C.",
	DE : "Delaware",
	FL : "Florida",
	GA : "Georgia",
	GU : "Guam",
	HI : "Hawaii",
	ID : "Idaho",
	IL : "Illinois",
	IN : "Indiana",
	IA : "Iowa",
	KS : "Kansas",
	KY : "Kentuck",
	LA : "Louisiana",
	ME : "Maine",
	MD : "Maryland",
	MA : "Massachusetts",
	MI : "Michigan",
	MN : "Minnesota",
	MP : "Northern Mariana Islands",
	MS : "Mississippi",
	MO : "Missouri",
	MT : "Montana",
	NE : "Nebraska",
	NV : "Nevada",
	NH : "New Hampshire",
	NJ : "New Jersey",
	NM : "New Mexico",
	NY : "New York",
	NC : "North Carolina",
	ND : "North Dakota",
	OH : "Ohio",
	OK : "Oklahoma",
	OR : "Oregon",
	PA : "Pennsylvania",
	PR : "Puerto Rico",
	RI : "Rhode Island",
	SC : "South Carolina",
	SD : "South Dakota",
	TN : "Tennessee",
	TX : "Texas",
	UT : "Utah",
	VT : "Vermont",
	VA : "Virginia",
	VI : "U. S. Virgin Islands",
	WA : "Washington",
	WV : "West Virginia",
	WI : "Wisconsin",
	WY : "Wyoming",
}